############################################
####    	Proyecto I: Haskell			####
####		Jack “El Monádico”Lambda	####
####		Carlos Rivero 13-11216		####
####		Jose Barrera 15-10123		####
############################################

#Makefile que nos permite compilar el codigo
#para el proyecto "jackLambda" facilmente

CC 			= ghc
TARGET 		= JackLambda
DEPENDENCY 	= Cartas

lambdaMake: JackLambda.hs
	$(CC) $(TARGET)
	rm *.hi *.o